name: Deploy Stage

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_STAGE }}/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"